name: CI-format-check

on:
  push:
    paths:
      - "**.h"
      - "**.c"
      - ".github/workflows/check-format.yml"
      - ".clang-format"
  pull_request:
    paths:
      - "**.h"
      - "**.c"
      - ".github/workflows/check-format.yml"
      - ".clang-format"

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.12
        with:
          source: "."
          clangFormatVersion: 12
          inplace: false
